version: "0.0.1"
name: "web_app"
mode: "dev"
port: 8080
host: "127.0.0.1"
start_time: "2022-03-01"
machine_id: 1

token:
  duration: 365

expire:
  post_expire: 30
  voted_expire: 7

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 3
  compress: false

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "bluebell"
  max_open_connection: 200
  max_idle_connecrtion: 50

redis:
  host: "192.168.141.101"
  port: 6379
  db: 1
  password : ""
  pool_size: 100