version: "0.0.1"
name: "web_app"
mode: "dev"
port: 8888
host: "0.0.0.0"
start_time: "2022-03-01"
machine_id: 1

token:
  duration: 365

expire:
  post_expire: 30
  voted_expire: 7

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 3
  compress: false

mysql:
  host: mysql
  port: 3306
  user: "root"
  password: "123456"
  dbname: "bluebell"
  max_open_connection: 200
  max_idle_connecrtion: 50

redis:
  host: redis
  port: 6379
  db: 0
  password : ""
  pool_size: 100